version: '3.6'
services:
  mysql_db: 
    image: mysql
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${DB_ROOT_HOST}
    ports:
      - '3308:3308'
    expose:
      - "3308"  
  starwars-api:
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql_db
    links:
      - mysql_db
    command: ["./wait-for-db.sh"]    
