version: '3.6'
services:
  mysql_db: 
    #build: ./db-setup
    image: mysql
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'starwars'
      MYSQL_USER: 'chibuzo'
      MYSQL_PASSWORD: 'untold'
      MYSQL_ROOT_PASSWORD: untold-root
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3308:3308'
    expose:
      - "3308"  
  starwars-api:
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql_db
    links:
      - mysql_db
    command: ["./wait-for-db.sh"]    
